### ISSUE TITLE
Great project! Prefer '===' to '==' in all cases

### ISSUE THREAD

**Issue by erose** [Action-Lab/list-of-projects#1]
@ilyankou Hi, I really like this project! A simple need filled in a simple way.

A bit of feedback: you likely don't want to use `==` in JS, as you do on lines https://github.com/Action-Lab/list-of-projects/blob/master/main.js#L84, https://github.com/Action-Lab/list-of-projects/blob/master/main.js#L149 and some other places, because it invokes [weird coercion rules](https://stackoverflow.com/questions/359494/which-equals-operator-vs-should-be-used-in-javascript-comparisons), which are rarely the behavior you want. Use `===` instead.

**Comment by JackDougherty** [comment]
@ilyankou - not sure if you saw this comment. Do you agree? Or think differently?

**Comment by ilyankou** [comment]
Agreed.
